name: 'format-json-yml'
author: 'dev-hato Development Team'
description: 'JSONやYAMLのフォーマットを整える'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: bash "${{ github.action_path }}/scripts/action/format.sh"
    - uses: dev-hato/actions-diff-pr-management@v1.1.3
      with:
        github-token: ${{inputs.github-token}}
        branch-name-prefix: fix-format-json-yml
        pr-title-prefix: formatが間違ってたので直してあげたよ！
