name: 'format-json-yml'
author: 'dev-hato Development Team'
description: 'JSONやYAMLのフォーマットを整える'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: find . -not -path './.github/workflows/*' -name '*.json' -exec yq -i -o json {} \;
    - shell: bash
      run: find . -not -path './.github/workflows/*' \( -name '*.yaml' -o -name '*.yml' \) -exec yq -i {} \;
    - uses: dev-hato/actions-diff-pr-management@v1.0.1
      with:
        github-token: ${{inputs.github-token}}
        branch-name-prefix: fix-format-json-yml
        pr-title-prefix: formatが間違ってたので直してあげたよ！
        repo-name: ${{inputs.repo-name}}
