name: 'format-json-yml'
author: 'dev-hato Development Team'
description: 'JSONやYAMLのフォーマットを整える'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: bash "${{ github.action_path }}/scripts/action/format.sh"
    - uses: reviewdog/action-suggester@v1
