name: "format-json-yml"
author: "dev-hato Development Team"
description: "JSONやYAMLのフォーマットを整える"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: bash "${{ github.action_path }}/scripts/action/format.sh"
    - shell: bash
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: npx prettier --write .
    - uses: dev-hato/actions-diff-pr-management@v1.2.0
      with:
        github-token: ${{inputs.github-token}}
        branch-name-prefix: fix-format-json-yml
        pr-title-prefix: formatが間違ってたので直してあげたよ！
        pr-description-prefix: formatが間違ってたので直してあげたよ！
