---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
permissions: read-all
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: dev-hato/github-actions-cache-cleaner@4c9ac284bf7eff3eef8c05c8fecc1df62dfbd4cc # v0.0.59
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
