---
name: update-gitleaks
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  update-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          cache: npm
      - name: Install packages
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: npm ci
      - uses: dev-hato/actions-update-gitleaks@03938dd5977a402407e294b9a056848f0e9d670e # v0.0.88
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
